version: "3"
 
services:
 
  web_1:
    image: nicopaez/password-api
  
  web_2:
    image: nicopaez/password-api
       
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - web_1
      - web_2
